# Generated by Django 3.1.2 on 2020-12-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_accessinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessinfo',
            options={'ordering': ('-access_time',)},
        ),
    ]
