# Generated by Django 3.1.2 on 2021-01-05 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_text1'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=200)),
                ('cityleader', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Keep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keep_year', models.CharField(max_length=4)),
                ('keep_num', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.city')),
            ],
        ),
    ]
