# Generated by Django 3.1.2 on 2021-01-07 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_adopt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Died',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('died_year', models.CharField(max_length=4)),
                ('died_num', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.city')),
            ],
        ),
    ]
